<?php
    echo '<header>
        <h1>JSON - JavaScript Object Notation</h1>
        <nav>
            <a href="index.php">Home</a>
            <a href="topic.php">Learn More About JSON</a>
            <a href="quiz.php">JSON Quiz</a>
            <a href="enhancements.html">Enhancements</a>
            <a href="enhancements2.html">Enhancements 2</a>
            <a href="manage.php">Admin</a>

        </nav>
        <hr />
    </header>'
?>